using BiometricPhotoChecker;

string photoPath = Path.Combine(Directory.GetParent(System.Environment.CurrentDirectory).Parent.Parent.FullName, "img", "biyo.png");
byte[] imageArray = System.IO.File.ReadAllBytes(photoPath);

BiometricPhotoValidationService service = new BiometricPhotoValidationService();
CheckInfo result = service.ValidateBiometricPhoto(imageArray);
Console.WriteLine(nameof(result.IsImageValid) + " - " + result.IsImageValid);
Console.WriteLine(nameof(result.IsSmileValid) + " - " + result.IsSmileValid);
Console.WriteLine(nameof(result.IsMouthValid) + " - " + result.IsMouthValid);
Console.WriteLine(nameof(result.IsNoseValid) + " - " + result.IsNoseValid);
Console.WriteLine(nameof(result.IsEyesValid) + " - " + result.IsEyesValid);
Console.WriteLine(nameof(result.IsHeadAndShouldersVisible) + " - " + result.IsHeadAndShouldersVisible);
Console.WriteLine(nameof(result.IsBackgroundValid) + " - " + result.IsBackgroundValid);
Console.WriteLine(nameof(result.IsProperLighting) + " - " + result.IsProperLighting);
Console.WriteLine(nameof(result.IsFacePositionValid) + " - " + result.IsFacePositionValid);
Console.WriteLine(nameof(result.IsEyePositionValid) + " - " + result.IsEyePositionValid);
Console.WriteLine(nameof(result.IsFaceDetected) + " - " + result.IsFaceDetected);
Console.WriteLine(nameof(result.IsFacialExpressionNeutral) + " - " + result.IsFacialExpressionNeutral);
Console.WriteLine(nameof(result.IsWithoutGlasses) + " - " + result.IsWithoutGlasses);
Console.WriteLine(nameof(result.AreEyesOpen) + " - " + result.AreEyesOpen);
Console.WriteLine(nameof(result.IsMouthClosed) + " - " + result.IsMouthClosed);
Console.WriteLine(nameof(result.IsGazeStraightAhead) + " - " + result.IsGazeStraightAhead);
Console.WriteLine(nameof(result.IsRedEyeAbsent) + " - " + result.IsRedEyeAbsent);
Console.WriteLine(nameof(result.IsFaceWellLit) + " - " + result.IsFaceWellLit);
Console.WriteLine(nameof(result.IsSkinTextureClear) + " - " + result.IsSkinTextureClear);
Console.WriteLine(nameof(result.AreColorsNotFaded) + " - " + result.AreColorsNotFaded);
Console.WriteLine(nameof(result.IsNotPixelated) + " - " + result.IsNotPixelated);
Console.WriteLine(nameof(result.IsSkinTextureNatural) + " - " + result.IsSkinTextureNatural);
Console.WriteLine(nameof(result.IsGlareAbsent) + " - " + result.IsGlareAbsent);
Console.WriteLine(nameof(result.IsNotOverexposed) + " - " + result.IsNotOverexposed);
Console.WriteLine(nameof(result.IsFaceNotTurnedSideways) + " - " + result.IsFaceNotTurnedSideways);
Console.WriteLine(nameof(result.IsGazeLevel) + " - " + result.IsGazeLevel);
Console.WriteLine(nameof(result.IsNotTooClose) + " - " + result.IsNotTooClose);
Console.WriteLine(nameof(result.IsNotTooFar) + " - " + result.IsNotTooFar);
Console.WriteLine(nameof(result.IsFaceNotTooHigh) + " - " + result.IsFaceNotTooHigh);
Console.WriteLine(nameof(result.IsFaceNotTooLow) + " - " + result.IsFaceNotTooLow);
Console.WriteLine(nameof(result.IsFaceNotTooLeft) + " - " + result.IsFaceNotTooLeft);
Console.WriteLine(nameof(result.IsImageSharp) + " - " + result.IsImageSharp);
Console.WriteLine(nameof(result.IsSaturationBalanced) + " - " + result.IsSaturationBalanced);
Console.WriteLine(nameof(result.IsBackgroundUniform) + " - " + result.IsBackgroundUniform);
Console.ReadKey();
